version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=blossom
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - blossom-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blossom
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - blossom-network

  redis:
    image: redis:6.2-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - blossom-network

volumes:
  mysql-data:
  redis-data:

networks:
  blossom-network:
    driver: bridge 